import Vue from "vue";
import VueRouter from "vue-router";


Vue.use(VueRouter);

const routes = [
  {
    path: "/",
    redirect:"/home"
  },
  {
    path:"/home",
    name:"home",
    component:()=>import("../views/Home"),
    children:[
      {
        path:"HomeDetailNotice",
        name:"HomeDetailNotice",
        component:()=>import("../components/HomeDetailNotice")
      }
    ]
  },
  {
    path:"/mycommunity",
    name:"mycommunity",
    component:()=>import("../views/MyCommunity"),
    children:[
      {
        path:"Menu",
        name:"Menu",
        component:()=>import("../components/functionMenu"),
        children:[
          {
            path:"InfoInput",
            name:"InfoInput",
            component:()=>import("../components/infoInput"),
            children:[
              {
                path:"ChoiceUser",
                name:"ChoiceUser",
                component:()=>import("../components/choiceUser")
              }
            ]
          },
          {
            path:"WaitCheck",
            name:"WaitCheck",
            component:()=>import("../components/waitCheck"),
            children:[
              {
                path:"InfoEdit",
                name:"InfoEdit",
                component:()=>import("../components/infoInput")
              },
              {
                path:"Check",
                name:"Check",
                component:()=>import("../components/check")
              },
              {
                path:"WaitCheckDetail",
                name:"WaitCheckDetail",
                component:()=>import("../components/checkHistoryDetail")
              }
            
            ]
          },
          {
            path:"CheckHistory",
            name:"CheckHistory",
            component:()=>import("../components/checkHistory"),
            children:[
              {
                path:"HistoryDetail",
                name:"HistoryDetail",
                component:()=>import("../components/checkHistoryDetail")
              }
            ]
          },
          {
            path:"MyUpload",
            name:"MyUpload",
            component:()=>import("../components/myUpload"),
            children:[
              {
                path:"MyUploadDetail",
                name:"MyUploadDetail",
                component:()=>import("../components/checkHistoryDetail")
              }
            ]
          },
          {
            path:"AccountManagement",
            name:"AccountManagement",
            component:()=>import("../components/accountManagement"),
            children:[
              {
                path:"Authority",
                name:"Authority",
                component:()=>import("../components/authority")
              }
            ]
          },
          {
            path:"AccountCheck",
            name:"AccountCheck",
            component:()=>import("../components/accountManagement")
          },
          {
            path:"CheckNotice",
            name:"CheckNotice",
            component:()=>import("../components/checkNotice"),
            children:
            [
              {
                path:"CheckChoiceUser",
                name:"CheckChoiceUser",
                component:()=>import("../components/choiceUser"),
                children:[
                  {
                    path:"AddUser",
                    name:"AddUser",
                    component:()=>import("../components/addUser")
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        path:"UserInfo",
        name:"UserInfo",
        component:()=>import("../components/userInfo"),
        children:[
          {
            path:"detailUserInfo",
            name:"detailUserInfo",
            component:()=>import("../components/detailUserInfo")
          },
          {
            path:"editUserInfo",
            name:"editUserInfo",
            component:()=>import("../components/editUserInfo")
          }
        ]
      },
      {
        path:"myNotice",
        name:"myNotice",
        component:()=>import("../components/myNotice"),
        children:[
          {
            path:"detailNotice",
            name:"detailNotice",
            component:()=>import("../components/detailNotice")
          }
        ]
      }
    ]
  },
  
  {
         path:"/login/:id",
         name:"login",
         component:()=>import("../views/Login")
  },
  {
    path:"/service",
    name:"service"
  }
  
];

const router = new VueRouter({
  routes
});

export default router;
